# -*- coding: utf-8 -*-
"""Cópia de Cópia de Pdf to image

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6LDYtDe8BIlJQuDq6J9n1Aq6w0t3Vku

Extract a text from a PDF
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install PyMuPDF Pillow

!pip install PyPDF2image

pip install PyPDF2

import fitz  # this is pymupdf

with fitz.open("") as doc:
    text = ""
    for page in doc:
        text += page.getText()

print(text)

"""PDF to Image

"""

!sudo apt install poppler-utils

pip install pdf2image

from pdf2image import convert_from_path
pages = convert_from_path('/content/drive/MyDrive/NF_Test/lot061021.pdf', 500)

for page in pages:
    page.save('Lot_06_10_21.jpg', 'JPEG')